VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsApp"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private mCn     As ADODB.Connection
    
Public Property Set cn(ByVal NewVal As ADODB.Connection)
    Set mCn = NewVal
End Property

Public Property Get cn() As ADODB.Connection
    Set cn = mCn
End Property


