Attribute VB_Name = "modDatabase"
Option Explicit

'********************** Individuals Table *****************************
Public Const gtcINDIVIDUALS As String = "Individuals"
    Public Const gccINDID As String = "indId"
    Public Const gccINDSURNAME As String = "indSurname"
    Public Const gccINDFIRSTNAMES As String = "indFirstNames"
    Public Const gccINDGENDER As String = "indGender"
    Public Const gccINDDOBTEXT As String = "indDOBText"
    Public Const gccINDDOBDATE As String = "indDOBDate"
    Public Const gccINDPLACEOFBIRTH As String = "indPlaceOfBirth"
    Public Const gccINDADOPTED As String = "indAdopted"
    Public Const gccINDBAPTDATETEXT As String = "indBaptDateText"
    Public Const gccINDBAPTDATEDATE As String = "indBaptDateDate"
    Public Const gccINDBAPTCHURCH As String = "indBaptChurch"
    Public Const gccINDDECEASED As String = "indDeceased"
    Public Const gccINDDEATHDATETEXT As String = "indDeathDateText"
    Public Const gccINDDEATHDATEDATE As String = "indDeathDateDate"
    Public Const gccINDPLACEOFDEATH As String = "indPlaceOfDeath"
    Public Const gccINDPLACEBURIED As String = "indPlaceBuried"
    Public Const gccINDADDLINE1 As String = "indAddLine1"
    Public Const gccINDADDLINE2 As String = "indAddLine2"
    Public Const gccINDADDLINE3 As String = "indAddLine3"
    Public Const gccINDTOWN As String = "indTown"
    Public Const gccINDCOUNTY As String = "indCounty"
    Public Const gccINDPOSTCODE As String = "indPostCode"
    Public Const gccINDPHONE As String = "indPhone"
    Public Const gccINDEMAIL As String = "indEmail"
    Public Const gccINDFATHERID As String = "indFatherID"
    Public Const gccINDMOTHERID As String = "indMotherID"
    Public Const gccINDMEMO As String = "indMemo"

Public Const gtcMARRIAGES As String = "Marriages"
    Public Const gccSPOHUSBANDID As String = "spoHusbandId"
    Public Const gccSPOWIFEID As String = "spoWifeId"
    Public Const gccSPOREMARRIED As String = "spoRemarried"
    Public Const gccSPOMARRIAGEDATEDATE As String = "spoMarriageDateDate"
    Public Const gccSPOMARRIAGEDATETEXT As String = "spoMarriageDateText"
    Public Const gccSPOMARRIEDAT As String = "spoMarriedAt"
    
Public Const gtcCENSUSHEADER As String = "CensusHeader"
    Public Const gccCNHID As String = "cnhId"
    Public Const gccCNHYEAR As String = "cnhYear"
    Public Const gccCNHCOUNTY As String = "cnhCounty"
    Public Const gccCNHCIVILPARISH As String = "cnhCivilParish"
    Public Const gccCNHECCPARISH As String = "cnhEccParish"
    Public Const gccCNHCOUNTYBOROUGH As String = "cnhCountyBorough"
    Public Const gccCNHWARD As String = "cnhWard"
    Public Const gccCNHRURALDIST As String = "cnhRuralDist"
    Public Const gccCNHPARLDIV As String = "cnhParlDiv"
    Public Const gccCNHTOWN As String = "cnhTown"
    Public Const gccCNHREF As String = "cnhRef"
    Public Const gccCNHADDRESS As String = "cnhAddress"

Public Const gtcCENSUS As String = "Census"
    Public Const gccCENID As String = "cenId"
    Public Const gccCENCNHID As String = "cencnhId"
    Public Const gccCENINDID As String = "cenIndId"
    Public Const gccCENNAME As String = "cenName"
    Public Const gccCENRELATION As String = "cenRelation"
    Public Const gccCENMARRIED As String = "cenMarried"
    Public Const gccCENAGEM As String = "cenAgeM"
    Public Const gccCENAGEF As String = "cenAgeF"
    Public Const gccCENOCCUPATION As String = "cenOccupation"
    Public Const gccCENEMPLOYER As String = "cenEmployer"
    Public Const gccCENWORKINGATHOME As String = "cenWorkingatHome"
    Public Const gccCENWHEREBORN As String = "cenWhereBorn"
    Public Const gccCENDEAFDUMBBLIND As String = "cenDeafDumbBlind"

Public Const gtcOPTIONS As String = "Options"
    Public Const gccOPTID As String = "optId"
    Public Const gccOPTVALUE As String = "optValue"

Public Const gtcIMAGES As String = "Images"
    Public Const gccIMGID As String = "imgId"
    Public Const gccIMGNAME As String = "imgName"
    Public Const gccIMGCAPTION As String = "imgCaption"
    Public Const gccIMGDATETEXT As String = "imgDateText"
    Public Const gccIMGDATEDATE As String = "imgDateDate"
    Public Const gccIMGNOTES As String = "imgNotes"

Public Const gtcIMAGELINK As String = "ImageLink"
    Public Const gccIMLIMGID As String = "imlImgId"
    Public Const gccIMLINDID As String = "imlIndId"

Public Const gtcHOTSPOTS As String = "HotSpots"
    Public Const gccHSPIMGID As String = "hspImgId"
    Public Const gccHSPSEQ As String = "hspSeq"
    Public Const gccHSPINDID As String = "hspIndId"
    Public Const gccHSPX1 As String = "hspX1"
    Public Const gccHSPX2 As String = "hspX2"
    Public Const gccHSPY1 As String = "hspY1"
    Public Const gccHSPY2 As String = "hspY2"
    Public Const gccHSPNOTE As String = "hspNote"

